name: rollbar_common
description: Commons package used by the Rollbar Dart and Flutter SDKs for error reporting.
version: 1.1.0
homepage: https://www.rollbar.com
documentation: https://docs.rollbar.com/docs/flutter#dart
repository: https://github.com/rollbar/rollbar-flutter

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  collection: ^1.17.2
  sqlite3: ^2.1.0
  uuid: ^3.0.7
  meta: ^1.9.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.9
  build_runner: ^2.4.6
  mockito: ^5.4.2
  pubspec_parse: ^1.2.3
