name: rollbar_flutter
description: Connect your Flutter applications to Rollbar for error reporting.
version: 1.5.0
homepage: https://www.rollbar.com
documentation: https://docs.rollbar.com/docs/flutter#flutter
repository: https://github.com/rollbar/rollbar-flutter

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.10.0
  connectivity_plus: ^5.0.1
  sqlite3_flutter_libs: ^0.5.17
  rollbar_common:
    git:
      url: https://github.com/brighttank/rollbar-flutter.git
      path: rollbar_common
  rollbar_dart:
    git:
      url: https://github.com/brighttank/rollbar-flutter.git
      path: rollbar_dart

#dependency_overrides:
#  rollbar_common:
#    path: ../rollbar_common
#  rollbar_dart:
#    path: ../rollbar_dart

dev_dependencies:
  lints: ^3.0.0
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  mockito: ^5.4.2

flutter:
  plugin:
    platforms:
      android:
        package: com.rollbar.flutter
        pluginClass: RollbarFlutterPlugin
      ios:
        pluginClass: RollbarFlutterPlugin
