name: rollbar_dart
description: Connect your Dart applications to Rollbar for error reporting.
version: 1.3.1
homepage: https://www.rollbar.com
documentation: https://docs.rollbar.com/docs/flutter#dart
repository: https://github.com/rollbar/rollbar-flutter

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  meta: ^1.9.0
  sqlite3: ^2.1.0
  collection: ^1.17.2
  stack_trace: ^1.11.0
  rollbar_common:
    git:
      url: https://github.com/brighttank/rollbar-flutter.git
      path: rollbar_common

dependency_overrides:
  rollbar_common:
    path: ../rollbar_common

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.9
  mockito: ^5.4.2
  build_runner: ^2.4.6
  pubspec_parse: ^1.2.3
